### ISSUE TITLE
Retry performance

### ISSUE THREAD

**Issue by soufianbenafia** [ptrd/kwik#11]
Hi i am measuring the Address Validation Using Retry Packets in KWIK in my home network.

for that reason i measured the time when the kwik server sends a retry to a client and the client sends back the retry answer with the same token to server and i found out that the latency incredibly high.

I used the timestamp when a retry is send and the timestamp when a server received a retry answer and subtracted them.

The confidence interval was between 173,04ms und  174,96ms. If i ping the same host in my home network the times are under 1 ms.

I am doing something wrong or kwik is incredibly  slow.

**Comment by ptrd** [comment]
See screenshots, for my results on loopback interface (so no network latency).
The first sample is client cold start: 60 ms. The second sample is when the client already has been started: 8 ms.
Whether this is fast or slow is a matter of perception ;-). But it is clear that the JVM startup behaviour has major impact.

<img width="1267" alt="Screenshot 2021-09-15 at 18 34 45" src="https://user-images.githubusercontent.com/1193474/133473836-b6ce2a27-6a76-4103-aa87-f99362a665d7.png">

<img width="1267" alt="Screenshot 2021-09-15 at 18 37 55" src="https://user-images.githubusercontent.com/1193474/133473961-2d7ded11-3d47-410f-b5af-484fafeca30c.png">

Cheers
Peter

**Comment by ptrd** [comment]
Update: with latest java (17), cold start time is reduced to 36 ms.
