### ISSUE TITLE
cannot find libs/flupke-plugin.jar 

### ISSUE THREAD

**Issue by abnv418** [ptrd/kwik#15]
As mentioned in the documentation I do not find this libs/flupke-plugin.jar to run the server code. I just find few jars here https://bitbucket.org/pjtr/flupke/downloads/ 

and I run the server using this command

java -Duser.language=en -Duser.country=US -cp build/libs/kwik.jar:flupke/flupke-9681a8c.jar net.luminis.quic.server.Server certs/ssl_cert.pem certs/ssl_key.pem 4433 /Desktop/root.

Can you please let me know if this is the correct jar file for starting the server ?

**Comment by abnv418** [comment]
The jar file can be created by downloading the flupke code and building it.

**Comment by ptrd** [comment]
Thanks for reporting and pull request. I just removed the old flupke downloads, as this can be quite confusing indeed.
