### ISSUE TITLE
kwik as client side connecting to quiche server still fails

### ISSUE THREAD

**Issue by xtuyaowu** [ptrd/kwik#22]
which version (commit) of Kwik? master branch
Java version? jdk11
OS? mac
which quiche version? 0.14.0

errorr log：

$ java -jar kwik.jar 127.0.0.1 4433 --noCertificateCheck -A hq-interop -c 10000     
59:11.046 Creating connection with 127.0.0.1:4433 with QUIC_version_1
59:11.206 Original destination connection id: 067f7ea1587eef5b (scid: 97360d28250625f6)
          >- CryptoStream[I|ClientHello]
59:11.478 <- (1) Packet I|-|R|69| Retry Token (18): 7175696368657f000001067f7ea1587eef5b
          >- CryptoStream[I|ClientHello,ClientHello]
59:11.477 -> Packet I|0|L|1200|2  Token=[] CryptoFrame[0,251] Padding(902)
59:11.659 -> Packet I|1|L|1200|2  Token=7175696368657f000001067f7ea1587eef5b CryptoFrame[0,251] Padding(872)
59:11.677 <- (2) Packet I|0|L|188|2  Token=[] AckFrame[1|Δ16] CryptoFrame[0,123]
          -< CryptoStream[I|ServerHello]
59:11.752 -> Packet I|2|L|1201|2  Token=7175696368657f000001067f7ea1587eef5b AckFrame[0|Δ0] Padding(1123)
59:11.677 <- (2) Packet H|0|L|1012|1  CryptoFrame[0,954]
          -< CryptoStream[H|EncryptedExtensions,Certificate]
59:11.837 Error: Inconsistency error in congestion controller; attempt to set bytes in-flight below 0
59:11.840 -> Packet H|0|L|58|1  AckFrame[0|Δ0]
59:11.677 <- (3) Packet H|1|L|300|1  CryptoFrame[954,241]
59:11.888 -> Packet H|1|L|88|2  AckFrame[1-0|Δ0] ConnectionCloseFrame[TLS 46|0|servername does not match]
Got IO error: java.net.ConnectException: Handshake error
This was quick, huh? Next time, consider using --http09 or --keepAlive argument.

@ptrd can you give your success command ?
thanks

**Comment by ptrd** [comment]
Hi,
This is a TLS error caused by the fact that the name on the server certificate (the "CN", common name) does not match the hostname (probably "localhost" when you are testing locally). 
To solve this, start quiche server with a properly named certificate (i.e. "CN=localhost"). This can be a self-signed certificate that you generate yourself.
In the meantime, i will see if i can TLS lib convince not to check the server name...   ;-)
Hth
Peter

**Comment by ptrd** [comment]
Fixed. If you check out https://github.com/ptrd/kwik/commit/dce6c41d0b4f88bbd3fd5497cbb682bca7d4820c you should be able to connect to quiche even if the server certificate does not contain the right hostname.

**Comment by oss-jtyd** [comment]
hi @ptrd Peter can you join slack and discuss direct: https://join.slack.com/t/wmjtyd/shared_invite/zt-1bhwmsd7o-3t_k2jwYwcbziHZW263xJQ
