### ISSUE TITLE
Kwik whether consider support SpringBoot built-in containers ?

### ISSUE THREAD

**Issue by XiaoZiShan** [ptrd/kwik#25]
Please see [Spring Boot in a Container](https://spring.io/blog/2018/11/08/spring-boot-in-a-container)

**Comment by ptrd** [comment]
Please formulate your question in a way that i can understand what you want. My time is as precious for me as it is for you. If you do not want to spend time or effort to clearly explain what you want, why should I spend time to answer it????

**Comment by XiaoZiShan** [comment]
> Please formulate your question in a way that i can understand what you want. My time is as precious for me as it is for you. If you do not want to spend time or effort to clearly explain what you want, why should I spend time to answer it????

Sir, I'm so sorry, not promptly reply your comments , because my country network unstable and my busy work too.

I  ready earnestly write my issue. 
+ Kwik can accord with to springboot container standard ?will  Kwik starter runing in springboot  container, such as tomcat, undertow, jetty ...
+ Kwik can  as one component used by other web containers ?
+ At present, there is no project on http3 in the spring ecosystem, what are your plan?

Sir, my waiting for your reply. 
Thank your comments!

**Comment by ptrd** [comment]
Kwik & Flupke are just implementations of the QUIC vs HTTP3 protocol. It's not a servlet engine like tomcat. You could build something on top of Kwik/Flupke to integratie it with tomcat. 
Spring boot is again another layer of abstraction on top of tomcat are any other servlet-container. Asking me whether i will support Spring is like asking a manufacturer of tyres when he will release a race car. Even though a tyre is an essential part for a race car, these are 2 complete different things.

Hope this helps.

**Comment by XiaoZiShan** [comment]
> Kwik & Flupke are just implementations of the QUIC vs HTTP3 protocol. It's not a servlet engine like tomcat. You could build something on top of Kwik/Flupke to integrate with tomcat. 
> Spring boot is again another layer of abstraction on top of tomcat are any other servlet-container. Asking me whether i will support Spring is like asking a manufacturer of tyres when he will release a race car. Even though a tyre is an essential part for a race car, these are 2 complete different things.
> 
> Hope this helps.

Sir, your analogy is amazing， i know this point，for example mybatis is a orm framework ，mybatis-spring is a spring adapter， mybaits-spring-boot-starter is a springboot adapter, these project are warpped in mybatis，can i do an adapter similar project for third party  integrate，is this a good idea for you at the moment?
