### ISSUE TITLE
Should google.com work?

### ISSUE THREAD

**Issue by lamasp** [ptrd/kwik#26]
I tried kwik now (master branch, latest rev) and using Java 11. Built from source and tried to connect to https://google.com:443/ but it returned an ALPN error. Looking at a packet capture, the ALPN is specified.

Should kwik CLI be able to contact google.com?

$ /usr/lib/jvm/java-11-openjdk/bin/java -jar ~/Downloads/kwik.jar -l D https://google.com:443/
Socket receive buffer size: 106496
Bytes in flight increased to 1200
Processing delay for packet #1: 0 ms
Parsing InitialPacket
Destination connection id (8): 53 fe 44 53 cc ba 99 78 
Source connection id (8): ef 0f 51 e0 ab e0 19 86 
Length (PN + payload): 97
Parsed packet with size 123; 0 bytes left.
14:02.370 Error: Connection closed by peer with TLS error 120: 28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol
Bytes in flight decreased with 1200 to 0 (1 packets RESET)
Processing delay for packet #2: 0 ms
Parsing InitialPacket
Destination connection id (8): 53 fe 44 53 cc ba 99 78 
Source connection id (8): ef 0f 51 e0 ab e0 19 86 
Length (PN + payload): 97
Parsed packet with size 123; 0 bytes left.
Terminating receiver loop because of interrupt
closing receiver
Sender thread is interrupted; probably shutting down? true
Got IO error: java.net.ConnectException: Handshake error

Re-run with more log flags added: 

$ /usr/lib/jvm/java-11-openjdk/bin/java -jar ~/Downloads/kwik.jar -l DpdrcsiwRS https://google.com:443/
17:08.106 Creating connection with google.com:443 with v1
Socket receive buffer size: 106496
17:08.184 Original destination connection id: 5783271686753c51 (scid: 242c35f486ba90eb)
Initial secret: 21 40 f2 8e 28 34 63 e7 f3 49 38 54 15 d6 8f 09 89 8f 35 3f 32 fe 12 f7 97 b0 0d 02 d6 04 04 ef 
Client initial secret: f3 79 08 e3 19 03 d1 0e eb 97 a1 a8 56 1d a0 cc 2d fc 75 27 3c 49 8a 26 b6 10 ab 40 d1 18 63 00 
Client key: ff 89 d0 1e b0 32 6e d5 a1 52 64 5a 8b 9e f2 72 
Client iv: ef a6 8a e7 f8 6c ae 6e 5f 5e 47 7a 
Client hp: ce cc d6 07 cc 3b fd ef 3d ff ef dd 43 c1 1d 78 
Server initial secret: 02 0d af c0 ce 7e 88 49 35 16 29 06 b9 0d 5f 30 19 39 02 de a0 47 89 bb f2 96 8f 91 df 28 4d 01 
Server key: 9a 8c 58 39 10 da c2 20 7d 9a 23 b6 4c 94 5c 93 
Server iv: 07 b6 3d ba 5c de ad 6f 97 2e 27 e8 
Server hp: 48 36 a2 c9 66 a8 0a 90 6a ff 05 9e 13 db cc d6 
          >- CryptoStream[I|ClientHello]
Client key: e2 b5 a1 87 ec 3a 83 48 10 2a 27 8e 42 61 be a7 
Client iv: 5a 24 6e ab 94 81 0b 68 22 92 0d 9c 
Client hp: 1b c4 eb 53 b3 17 6e 00 fa f1 55 b9 30 bb d4 83 
packet sent, pn: 0 (1200): 
c8 00 00 00 01 08 57 83  27 16 86 75 3c 51 08 24 
2c 35 f4 86 ba 90 eb 00  44 96 5a 55 2e 88 a2 b1 
24 11 42 df 44 9c c1 b0  46 81 58 bd 90 6c f6 12 
af 4a 29 2d 3f c6 a4 69  e7 3c ac af 6c 67 9b af 
f6 ce 66 1d 08 1b 13 25  e1 c2 2b 50 06 95 7b c3 
b0 31 b5 4f 1e 79 d9 0b  80 38 54 18 36 1d 80 20 
b9 b6 7d 2c b5 8c 1d b5  e4 52 87 c5 1c c0 c9 7d 
f1 62 a2 ba c4 f4 b0 61  54 7f db ae eb a4 d4 80 
cc 8d 6b bb 13 2f 65 f6  d5 fa 15 9c 26 6e 3a 8d 
28 97 9d 78 cb 85 eb 8f  3b 55 08 29 dc 42 3b ab 
cb f1 00 b6 80 89 4e cb  bf 3e 2c 88 99 79 f7 8b 
08 6a e4 e1 29 31 05 a3  92 d3 11 f4 48 8b 4e 4e 
46 c1 e2 c7 5e e5 e9 0c  f8 6f 62 9d 37 e5 15 8c 
75 99 fd e3 b7 18 79 88  d1 27 c5 fe 61 c9 85 ea 
4a 02 c2 68 03 c2 09 ea  ba 3f 69 73 f3 12 99 1c 
0d 6e 33 45 e2 3e f8 90  ac 6d 44 51 c2 07 39 93 
75 af 7e a3 8a c9 fe c2  e7 23 3b 62 97 1c a8 27 
64 1d 45 3a 67 53 c4 4c  75 1e 53 8e 14 70 20 9c 
1d 36 11 7d 95 b5 b3 08  cb 98 b4 a6 c6 44 6e 4f 
5a 87 0d 4f 77 29 f8 0d  68 5d 12 cf 18 a4 06 d8 
28 5a 08 e9 f9 bd 65 f8  d0 4b 91 42 eb 6a 7d 7c 
8e 36 ad bf 2d a7 de e7  59 c2 30 c2 91 de b3 0a 
a1 b0 6f 20 a0 dd 51 fc  0d 5d 30 57 18 35 5e 26 
f8 d8 a0 00 84 6f d8 93  1f b3 46 df 51 32 75 5f 
f8 f8 49 20 fe a7 61 eb  26 3f 86 a0 98 13 3d ce 
26 b3 09 6e 24 b4 f8 df  fc 45 7c b2 80 8d 5c 03 
a0 cc 43 2a fd 57 7f 31  51 89 41 52 0f e3 86 f3 
33 de 22 04 ee bc e9 75  f8 4c 47 af 27 bb ab 10 
ab ec 07 5f 59 bf dd 00  1f 9f 0d b9 8c bd e2 22 
73 a2 01 9e 9f a0 95 02  4e 9c 69 48 b6 80 18 5f 
45 dd da 44 71 b9 8e 07  34 2a 57 bd ba 4a 67 92 
10 e9 3e 0a cd ef 21 4c  3b 72 d0 a0 4b d9 ee c6 
47 5a 51 35 0d 34 84 6e  a0 6a 3c 8d 95 49 b4 fe 
ad 29 e0 be aa fd d1 3a  59 cf 22 c6 dc ed be d7 
be 48 bb 66 de 7b 5c 57  8c 27 0f de cc 27 9f 5d 
9e e5 90 27 84 65 54 b2  4d b1 c9 73 96 06 af ac 
87 a8 dc 35 69 34 e0 6e  64 66 54 80 a7 1b 59 9d 
c4 11 63 12 c3 64 20 5c  00 07 4e 7c 64 9e c8 6d 
f1 41 52 2d 2f 5c 3c 6d  ea 28 ae 40 bc 5a 6d 4b 
e5 b8 cb ea bb 86 af dc  10 ff 3f 5e 90 96 75 7d 
98 c7 bd 81 ce 1b de 55  8a 6e 6f b0 c0 90 f5 13 
6d 1e 81 28 77 17 88 55  67 ef 9d ea 8e 95 77 d5 
f2 5a bc 35 75 2b 48 1b  93 7b 73 fb 48 f5 ca 2e 
d7 1d fc 03 0d 86 9e 0c  76 2b 01 8c 10 56 1d 1d 
8d db 93 81 e4 0d bc 8a  bb 3d 19 72 2a d2 3d 81 
28 f5 f9 fa 08 e3 ed c0  d6 2e 27 d6 03 6b 6d 0a 
e4 5e 84 d8 39 31 0f cd  57 e1 90 0e d4 f3 cc 50 
06 52 7d 43 6e a0 0c df  22 51 b4 15 fc 77 82 ee 
7b 6f a2 0a fe f6 b0 2f  06 a6 36 07 7f ea 40 0e 
4f 1d 21 ef e1 d1 dd e5  a0 18 de b0 87 df 89 3d 
3d 84 0f ac ad f6 23 0a  50 48 82 d7 f5 26 7e 68 
c7 cd 73 0e 43 80 a8 73  a5 a4 bd c1 23 39 90 6c 
1e dc 0e 52 2c 31 f6 f3  97 bd c3 8f 6a 56 04 e8 
95 14 da 2e 18 39 36 50  47 d6 65 56 74 08 dc ec 
f2 d3 e4 1c 31 d5 84 51  06 8f cb 21 65 1e 38 38 
68 21 61 cc 68 64 4d 15  35 ad 7a 04 88 dd c9 ba 
24 79 ce 99 01 34 d0 0d  14 2c c2 cf 74 86 2d a3 
8e 5d 3c 0f 0f 91 27 74  f4 59 ef 59 f0 3b 47 53 
e5 9a 2d e5 55 38 32 fd  7c 8b 0a e1 7d 4e 21 5c 
dd 47 58 ac cc aa ac e1  10 e6 51 c5 c6 c6 6d 0a 
7d d4 72 00 fe 3e 79 19  aa df f0 04 61 8b b0 0e 
e1 e4 fe c0 2d 78 2b f9  6b 9c 0e b3 6c 8e c3 64 
6d df ff 6a ba 08 ef f2  c3 89 2a 67 68 50 42 cb 
c0 3b b9 74 dc 0b 05 82  17 1d 98 6d 5e f7 52 8e 
1c a8 47 da f1 40 45 a2  05 cd a3 ec e0 40 07 a1 
fc f4 5a 7c ce e8 00 7e  00 1f 44 40 6b 5b 9b 87 
f3 ee 43 0a fa d6 e6 cb  12 8b 2f 2d 9f 44 1b 6e 
34 16 58 f0 c7 cc b5 6f  cb 5a 20 3c 68 3b ec ad 
83 92 00 7d 63 6e db ec  1e 88 0d 84 42 db 25 90 
b0 40 6f 65 12 c5 04 9f  08 29 e7 09 83 fd 7c 1e 
6a 3f d3 f2 99 16 05 9c  22 5a 60 41 dd e5 69 7d 
c1 d7 3e a0 cd 9e 50 9f  14 d5 83 07 f4 2a 11 62 
10 18 d2 e1 3c 16 0d f3  db 1d a9 8c f6 d6 2b d8 
0c 46 25 1b 14 15 bf 0d  ea 1f 78 8a 67 2c 6e 59 
e0 7c fb 00 a5 92 e5 22  3a c0 39 ac e0 54 b0 5b 
Bytes in flight increased to 1200
17:08.339 getPtoTimeAndSpace: no ack eliciting in flight and no handshake keys -> probe Initial
reschedule loss detection timer for PTO over 996 millis, based on 17:09.340/Initial, because peerAwaitingAddressValidation ackElicitingInFlight | RTT:500/125
17:08.331 -> Packet I|0|L|1200|2  Token=[] CryptoFrame[0,252] Padding(901)
Start processing packet 1 (123 bytes) (123): 
c3 00 00 00 01 08 24 2c  35 f4 86 ba 90 eb 08 d7 
83 27 16 86 75 3c 51 00  40 61 b7 11 ab ef 56 d3 
7e dd 08 9d 0a e2 64 59  57 7e b4 ed fa ac 27 3e 
58 c2 62 d9 7c 7c 09 4d  f1 58 fe 76 f8 09 94 33 
ca fc 74 82 ed a2 a4 0f  1d 1d 74 68 ef 7e 6b ee 
fd e1 dc e2 f4 d1 2b 09  dc 92 40 9a 19 bf 9c 88 
f9 8b eb 56 d5 de ce 02  fb af 4a 90 2a 95 54 ee 
5b 8a fc 7f 2b 34 bd f3  5e 29 b9 
Processing delay for packet #1: 0 ms
Parsing InitialPacket
Destination connection id (8): 24 2c 35 f4 86 ba 90 eb 
Source connection id (8): d7 83 27 16 86 75 3c 51 
Length (PN + payload): 97
Unprotected packet number: 1
Decrypted payload (80): 
1c 41 78 06 40 4a 32 38  3a 54 4c 53 20 68 61 6e 
64 73 68 61 6b 65 20 66  61 69 6c 75 72 65 20 28 
45 4e 43 52 59 50 54 49  4f 4e 5f 49 4e 49 54 49 
41 4c 29 20 31 32 30 3a  20 6e 6f 20 61 70 70 6c 
69 63 61 74 69 6f 6e 20  70 72 6f 74 6f 63 6f 6c 
17:08.470 <- (1) Packet I|1|L|123|1  Token=[] ConnectionCloseFrame[TLS 120|6|28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol]
Parsed packet with size 123; 0 bytes left.
17:08.502 Error: Connection closed by peer with TLS error 120: 28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol
Bytes in flight decreased with 1200 to 0 (1 packets RESET)
packet sent, pn: 1 (1201): 
c0 00 00 00 01 08 d7 83  27 16 86 75 3c 51 08 24 
2c 35 f4 86 ba 90 eb 00  44 97 90 ac 07 76 f1 33 
fa d3 d9 45 d2 31 a2 1c  7a ad 6c d7 e4 e4 6b 28 
25 86 88 88 48 e2 43 33  b8 ec 2e b3 0b bc b3 e3 
08 19 98 a2 e3 0e 69 a4  b6 d3 bf c7 87 6d 14 d4 
21 31 40 4d e3 b2 25 05  7f e0 b2 3a ec 05 1e 10 
d7 9e a0 43 5c 24 5c f0  44 5d a4 27 70 72 78 3d 
1f 18 ef 26 19 6d 09 9d  ea fe 0f 17 75 73 ab 2d 
15 60 3f 48 41 ae 2e 5d  35 22 5f ec 29 a5 47 cf 
a1 ca d8 cc 3d cd 24 96  38 fd 36 36 7f cf 1e 35 
65 04 25 52 0f da 58 27  38 4a 04 96 46 d5 97 a2 
cf 3c 4f 08 b4 5b 0a 7d  21 0c b1 53 88 92 99 bc 
61 a3 12 91 e4 13 d3 cf  82 5c cd 5c ae 21 1c de 
50 32 bb e4 96 5a 75 8a  6b f5 5f 97 59 34 10 fe 
21 58 16 65 1b 62 db 06  40 cf b0 84 c8 b7 18 d9 
38 22 5a 6b 64 f4 0f 61  51 cc 45 01 91 a2 fb 02 
21 d4 8b d8 89 43 2b 48  e1 97 29 f4 58 67 51 5b 
9a 0c fd 8d cd 78 63 a3  c0 36 04 be b1 be 38 ec 
7b a2 a6 c6 89 1f 00 66  c0 d4 1e f8 76 e3 dc 69 
c2 14 18 b0 9a 95 5b 66  4a fd 09 ef bf e7 04 98 
af 13 1a 6e 09 c5 0a 89  a6 c6 18 23 e2 c1 09 1f 
2e 8a a1 54 6a 39 d2 c8  fc 52 cb 06 4b 05 9f f1 
a1 a3 4d 31 82 d3 7d 0b  dd 85 4b 18 87 1d 96 2c 
31 ff b6 19 42 f5 e8 a5  22 7b 4a cf c8 5a 31 da 
ad f6 cf 81 b8 33 56 6b  97 02 63 1f dc 31 0f d8 
69 50 0f 4c dc a7 7e 51  51 3a af 40 6c 85 a5 da 
6c e0 79 88 5d 6d 30 4a  57 d8 8b fc 5c 99 da 59 
44 b8 02 29 9d d9 04 77  38 d5 bf 40 15 b3 82 11 
1d a8 b9 3b f2 86 de 3d  ed 4a 62 37 4f e8 94 7a 
46 ea a1 7f df e5 5d e5  9d 96 c4 f4 3d 5c 3f 7e 
50 c1 d7 c7 8c 52 65 14  78 3a 4e 75 1e 77 8e 5d 
97 a8 2b 67 ba 45 82 dd  36 73 3e 7c bb 86 eb 15 
55 e1 9c 71 72 0f 00 c3  38 d0 66 10 9d c0 31 5c 
30 22 5c 0e 77 92 a7 53  7c 40 2e 98 66 07 19 07 
c6 9d cf d5 02 39 18 af  01 56 f8 e8 b8 4d 73 cb 
cf 01 2f 32 57 da 15 1b  17 72 1d e2 40 85 43 1a 
cd 02 fc 85 3f 5c 41 4d  b0 7a 5f bb 94 e5 fb 9f 
dd 3f 7a c6 bd fd 86 0d  93 99 cc 34 df 9f 7f 96 
f4 6e bd c2 fc f0 cf 25  00 4c 42 7f d7 62 15 3f 
1a b1 f2 69 79 a2 13 0c  c0 07 d2 93 92 df 35 ee 
8c 5b a7 57 06 a3 16 b5  d6 70 bf c5 2b 05 c5 7e 
98 00 fb eb 09 d8 e5 a5  35 f1 2f 47 fc fc 97 5d 
57 f5 da e9 17 6e 53 3d  41 5c d5 06 1d 37 f7 92 
d9 36 2b 74 67 58 d7 3c  25 2f b1 8d d8 2c bb 97 
69 63 f3 1b 25 18 4f 0a  b5 32 83 27 a9 72 7d fb 
4d 19 b0 84 c3 47 41 cc  6b 9c 27 64 f4 e6 79 9a 
2e a1 dd 41 9c 91 50 39  c5 11 65 1a ea c1 d9 45 
cc 0f 38 8f 22 ab dc b7  e0 1d be a3 26 ab 9d 05 
27 e0 3c ff 8f 23 d8 64  74 b1 ee 43 03 9b c9 89 
ca 86 18 35 cc fa ec 59  79 35 d8 b3 a0 24 82 cd 
32 53 44 fe 85 9d 82 67  9a db 0c ad af 7a 31 4c 
1d e5 2d 88 8e 4b 73 60  28 96 5c e9 20 57 23 37 
fe 70 c0 63 dd db fc 81  a0 75 f5 c1 a4 e9 89 22 
9b 55 64 5a 47 81 b0 68  af b4 be f9 12 fd 45 fb 
9a ff 7e df 90 6a 15 6a  8b 31 78 15 26 7c dc 5f 
f9 c8 e1 1a 7f b5 4d fb  8d 79 7d 20 bc 22 de c4 
92 4c 4d e0 1f 34 92 d6  eb f4 31 b1 e3 30 9e 11 
21 61 2e a5 14 8a b4 97  bc 64 5b 76 69 91 7a c4 
51 bc 7c 8b 71 d5 ea 73  8c 38 c9 2a 76 a5 31 b4 
11 af bb 2d 6c 5d a8 eb  56 14 94 e4 a2 c0 58 e7 
85 a4 06 12 81 a2 71 56  e6 bd a7 fa 51 29 cf d4 
0a f3 7e ba 1a 39 01 94  b4 d6 3c c9 18 a3 c4 fe 
ae cd 67 27 84 7f 7a b8  07 5a 23 fe f0 69 cf 72 
53 df 9f 42 e2 ba 26 4b  48 11 c2 36 3c de 22 a3 
20 47 37 4a 40 79 04 73  17 20 db a6 42 f6 2a 90 
a9 2f ad 2d 6a fd cc 33  03 4d 62 3d 38 06 37 f7 
e4 28 b9 66 35 92 e4 22  55 87 21 a7 45 08 fd 9b 
44 ec d9 00 ef 2b 51 57  da 5d f6 5e 28 47 3f 0b 
fa 53 9d 9e 3f 90 c6 7b  da f2 39 88 cb 6f 9b a5 
db c5 76 40 70 73 27 72  22 15 5b 80 25 40 f7 d3 
cd 3e 73 85 a8 ce dd 3d  75 29 30 27 0d b5 f0 92 
60 17 65 95 24 11 92 24  fc 39 71 07 25 69 ad 32 
61 5f ce fb 3d 98 a0 57  5e 41 82 37 54 9a 55 2c 
a4 36 4a e1 8f 91 c0 cf  fb f0 48 f0 65 de fa 81 
53 3c 3e d6 be 7a 99 ea  58 e9 a9 54 f4 a6 21 5c 
51 
17:08.519 -> Packet I|1|L|1201|3  Token=[] ConnectionCloseFrame[0|0|] AckFrame[1|Δ0] Padding(1149)
Start processing packet 2 (123 bytes) (123): 
c3 00 00 00 01 08 24 2c  35 f4 86 ba 90 eb 08 d7 
83 27 16 86 75 3c 51 00  40 61 b7 11 ab ef 56 d3 
7e dd 08 9d 0a e2 64 59  57 7e b4 ed fa ac 27 3e 
58 c2 62 d9 7c 7c 09 4d  f1 58 fe 76 f8 09 94 33 
ca fc 74 82 ed a2 a4 0f  1d 1d 74 68 ef 7e 6b ee 
fd e1 dc e2 f4 d1 2b 09  dc 92 40 9a 19 bf 9c 88 
f9 8b eb 56 d5 de ce 02  fb af 4a 90 2a 95 54 ee 
5b 8a fc 7f 2b 34 bd f3  5e 29 b9 
Processing delay for packet #2: 0 ms
Parsing InitialPacket
Destination connection id (8): 24 2c 35 f4 86 ba 90 eb 
Source connection id (8): d7 83 27 16 86 75 3c 51 
Length (PN + payload): 97
Unprotected packet number: 1
Decrypted payload (80): 
1c 41 78 06 40 4a 32 38  3a 54 4c 53 20 68 61 6e 
64 73 68 61 6b 65 20 66  61 69 6c 75 72 65 20 28 
45 4e 43 52 59 50 54 49  4f 4e 5f 49 4e 49 54 49 
41 4c 29 20 31 32 30 3a  20 6e 6f 20 61 70 70 6c 
69 63 61 74 69 6f 6e 20  70 72 6f 74 6f 63 6f 6c 
17:08.656 <- (2) Packet I|1|L|123|1  Token=[] ConnectionCloseFrame[TLS 120|6|28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol]
Parsed packet with size 123; 0 bytes left.
closing receiver
Terminating receiver loop because of interrupt
Got IO error: java.net.ConnectException: Handshake error
Sender thread is interrupted; probably shutting down? true

**Comment by ptrd** [comment]
Hi,

Yes, but you need the flupke plugin for this (which, when present) is automatically put on the classpath by the kwik.sh script):
```
 ./kwik.sh -H / -ln google.com
Server returns:
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

The reason is that Kwik is a QUIC library and does not support HTTP3 by itself. When using the KwikCli, it has a fallback to "HTTP 0.9", which was used by the early quic implementations for easy testing (and is still used by the quic-interop). The error-message from Google is somewhat misleading, as the problem is not there is no alpn, but that the given alpn is not supported by google.com.

Hth
Peter

**Comment by lamasp** [comment]
Ah of course, thank you!
