### ISSUE TITLE
some errors in build (failing tests)

### ISSUE THREAD

**Issue by lhou705** [ptrd/kwik#3]
Hi，when I wang to build the lib,some errors occured.My gradle version is 5.3.1 with JDK 11
![1](https://user-images.githubusercontent.com/64344368/108515111-ae370380-72ff-11eb-8bc9-d566ec1af7d7.PNG)
![2](https://user-images.githubusercontent.com/64344368/108515172-bc851f80-72ff-11eb-816e-545dd9d85769.PNG)
So,how can I solve the problems above? Or could you please release a lib?

**Comment by ptrd** [comment]
Hi,

I know it's bad, but some tests (like these) are timing dependent and sometimes fail. Just build without the test, e.g. gradle assemble.

Hth
Peter

**Comment by ptrd** [comment]
This is (finally) fixed, these tests are not time dependent anymore.
