### ISSUE TITLE
Retention of unused encryption keys.

### ISSUE THREAD

**Issue by QUICTester** [ptrd/kwik#31]
The unused encryption keys, such as the Initial key, should be discarded once QUIC has moved to the Handshake encryption level (https://www.rfc-editor.org/rfc/rfc9001#name-discarding-unused-keys), same as the Handshake key after moving to the 1-RTT encryption level.

**Comment by ptrd** [comment]
Fixed (by https://github.com/ptrd/kwik/commit/040b0d1327bfb0a8e35c23c2bd612a4a39b721d4)
