### ISSUE TITLE
No state machine in TLS engine.

### ISSUE THREAD

**Issue by QUICTester** [ptrd/kwik#32]
The TLS engine (Agent 15) Kwik uses does not have a state machine. In other words, the TLS engine does not track the current state of the connection. If a Client Hello message is sent twice, the cryptographic parameter in the latter Client Hello will overwrite the previously computed cryptographic parameter from the first Client Hello message. The overwrite behavior can happen at any connection state, including after the connection is established. This also applies to the Finished message.

**Comment by ptrd** [comment]
Fixed.
Thanks for reporting!
