### ISSUE TITLE
Detecting connetion lost

### ISSUE THREAD

**Issue by DanielViniciusAlves** [ptrd/kwik#34]
I've been facing challenges while trying to handle connection losses to the server. It's likely because I lack sufficient knowledge of the language and library. However, I'm wondering if there's a simpler way to detect connection losses without having to create a heartbeat mechanism.

Currently, I am handling the connection as follows:

            try {
                while (connected) {
                    final short messageType = mConnectionDataInput.readShort();
                    final int messageLength = mConnectionDataInput.readInt();

                    final byte[] data = new byte[messageLength];
                    mConnectionDataInput.readFully(data);

                   // do something with the message
                }
            } catch (Exception e){
                // Handle error
            }
            

Despite my attempts to replicate the approach I use with TCP, I couldn't successfully detect the loss of connection with the server. The communication flow is different in this case, and I'm struggling to identify the right approach to make it work. This method, however, works fine with TCP.

I imagine this is more of a issue I have with the language and understanding how exception handling works in the context of Java, but it would be of great help if someone could guide me through it.

**Comment by ptrd** [comment]
When the connection is closed, either explicitly or due to an idle timeout, all open streams are aborted. The caller reading on the stream will get an IOException with the message "Connection closed". So, something like this should work:

```
        QuicStream quicStream = connection.createStream(true);
        InputStream input = quicStream.getInputStream();
        try {
            byte[] data = input.readAllBytes();
        }
        catch (IOException e) {
            // IOException during read means connection is closed or stream is closed or reset.
        }
```

Hth,
Peter

**Comment by ptrd** [comment]
@DanielViniciusAlves: any follow up? If not, I'd like to close this issue.
