### ISSUE TITLE
Are there plans to support RFC9221?

### ISSUE THREAD

**Issue by MysteryAngle** [ptrd/kwik#35]
[RFC9221](https://datatracker.ietf.org/doc/html/rfc9221) (An Unreliable Datagram Extension to QUIC)

> These features can be useful for optimizing audio/video streaming applications, gaming applications, and other real-time network applications.

**Comment by ptrd** [comment]
Yes. But currently i'm busy with other improvements, need to finish them before I start with a new topic.

**Comment by ptrd** [comment]
https://github.com/ptrd/kwik/commits/datagram/

Samples ("siduck"):
https://github.com/ptrd/kwik/blob/datagram/samples/src/main/java/net/luminis/quic/sample/siduck/SiduckClient.java
https://github.com/ptrd/kwik/blob/datagram/samples/src/main/java/net/luminis/quic/sample/siduck/SiduckServer.java

**Comment by ptrd** [comment]
Included in release 0.9
