### ISSUE TITLE
Parsing of Application Protocol Error Codes

### ISSUE THREAD

**Issue by WesleyRosenblum** [ptrd/kwik#4]
From the QUIC Transport RFC [§20.2](https://tools.ietf.org/id/draft-ietf-quic-transport-34.html#name-application-protocol-error-):

> The management of application error codes is left to application protocols. Application protocol error codes are used for the RESET_STREAM frame (Section 19.4), the STOP_SENDING frame (Section 19.5), and the CONNECTION_CLOSE frame with a type of 0x1d (Section 19.19).

The application error codes for these frames are encoded as variable-length integers, which should allow for a maximum value of 2^62-1, according to [§16](https://tools.ietf.org/id/draft-ietf-quic-transport-34.html#name-variable-length-integer-enc).

Kwik is parsing the application protocol error codes from these frames as `int`, which has a maximum value of 2^31-1:
- [ResetStreamFrame.java](https://github.com/ptrd/kwik/blob/8121464b6ae044294a3f9a4bd2cc4d59bdd72bf3/src/main/java/net/luminis/quic/frame/ResetStreamFrame.java#L44)
- [ConnectionCloseFrame.java](https://github.com/ptrd/kwik/blob/8121464b6ae044294a3f9a4bd2cc4d59bdd72bf3/src/main/java/net/luminis/quic/frame/ConnectionCloseFrame.java#L58)
- [StopSendingFrame.java](https://github.com/ptrd/kwik/blob/8121464b6ae044294a3f9a4bd2cc4d59bdd72bf3/src/main/java/net/luminis/quic/frame/StopSendingFrame.java#L48)

Could the parsing of application protocol error codes for these frames be changed to use the [parse_long method](https://github.com/ptrd/kwik/blob/8121464b6ae044294a3f9a4bd2cc4d59bdd72bf3/src/main/java/net/luminis/quic/VariableLengthInteger.java#L43)? In general, it may be better to use `parse_long` to avoid throwing exceptions on valid variable-length integers.

Thanks for considering this issue and let me know if you need any further information!

**Comment by ptrd** [comment]
Hi Wesley,
Sorry for the late response, i missed the notification email. Thanks for your feedback. You are right, parsing to a long would be better. I'll put it on my todo list! 
Regards,
Peter

**Comment by ptrd** [comment]
This is now fixed. Most frame parsers use parseLong, except in a few cases where a value larger than 2^31-1 is impossible or not supported by Kwik. Most notably: when the stream-id is larger than 2^31-1, Kwik currently "only" supports up to 2^31-1 streams. I don't think this will be a problem in practice (and if it does, i'll fix it then). As a side-effect of this fix, Kwik now also supports streams larger than 2^31-1, which is a nice improvement.
Thanks for reporting.
