### ISSUE TITLE
Android Connection timeout

### ISSUE THREAD

**Issue by jjjjjim20** [ptrd/kwik#49]
I'm trying to connect android device and my local server but I get connection time out in android client this is my log I can't find my problem. 
Thanks in advance

```
> Socket receive buffer size: 212992
>   SECURITY WARNING: INSECURE configuration! Server certificate validation is disabled; QUIC connections may be subject to man-in-the-middle attacks!
>   Original destination connection id: 99851f84feaec663 (scid: 5354ca6d3ec79f3c) >- CryptoStream[I|ClientHello]
>   Bytes in flight increased to 1200
>   Packet I|0|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 2400
>   Packet PI|1|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 3600
>   Packet PI|2|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 4800
>   Packet PI|3|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 6000
>   Packet PI|4|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 7200
>   Packet PI|5|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight decreased with 7200 to 0 (6 packets RESET)
>   closing receiver
>   Terminating receiver loop because of interrupt
```

**Comment by ptrd** [comment]
I'm certainly willing to help, but I really wonder how expect me to help you. What do you do when you get a connection timeout on a TCP connection?

**Comment by jjjjjim20** [comment]
this is my client code for connection:
        val log = SysOutLogger()
        log.logPackets(true)
        log.logInfo(true)
        log.logDebug(true)
        log.logCongestionControl(true)


        val connection = QuicClientConnection.newBuilder()
            .uri(URI.create("https://192.168.204.52:8201"))
            .applicationProtocol("h3") // Replace "h3" with the desired application protocol            .build()
            .logger(log)
            .build()
        
        connection.connect()
        
        this is my server code:
         List<Version> supportedVersions = new ArrayList<>();
        supportedVersions.add(Version.QUIC_version_1);
        supportedVersions.add(Version.QUIC_version_2);

        ServerConnectionConfig serverConnectionConfig = ServerConnectionConfig.builder()
                .maxIdleTimeoutInSeconds(30)
                .maxUnidirectionalStreamBufferSize(1_000_000)
                .maxBidirectionalStreamBufferSize(1_000_000)
                .maxConnectionBufferSize(10_000_000)
                .maxOpenPeerInitiatedUnidirectionalStreams(10)
                .maxOpenPeerInitiatedBidirectionalStreams(100)
                .maxIdleTimeoutInSeconds(120)
                .retryRequired(true)
                .connectionIdLength(8)
                .build();

        ServerConnector.Builder builder = ServerConnector.builder()
                .withPort(port)
                .withSupportedVersions(supportedVersions)
                .withConfiguration(serverConnectionConfig)
                .withCertificate(new FileInputStream(certificateFile), new FileInputStream(certificateKeyFile))
                .withLogger(log);

        ServerConnector serverConnector = builder.build();
        
        I don't set any thing to set use TCP I thing use UDP by defualt

**Comment by ptrd** [comment]
Did you start the connector?

**Comment by jjjjjim20** [comment]
yes I started after register http3:

```
         registerHttp3(serverConnector, wwwDir, log);
         serverConnector.start();
```

**Comment by ptrd** [comment]
2. What results do you get when not running on Android?

**Comment by jjjjjim20** [comment]
this is the android log:

```

> FATAL EXCEPTION: DefaultDispatcher-worker-1
>                                                                                                     Process: com.google.quicstream, PID: 21098
>                                                                                                     java.net.ConnectException: Connection timed out after 10000 ms
>                                                                                                     	at net.luminis.quic.core.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:368)
>                                                                                                     	at net.luminis.quic.core.QuicClientConnectionImpl.connect(QuicClientConnectionImpl.java:321)
>                                                                                                     	at com.google.quicstream.capture.capture.VideoRecorder$startRecording$1.invokeSuspend(VideoRecorder.kt:398)
>                                                                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>                                                                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>                                                                                                     	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
>                                                                                                     	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
>                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
>                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
>                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
>                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
>                                                                                                     	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a8fe386, Dispatchers.IO]

```

and this is a kwik log:

```
> Socket receive buffer size: 212992
>   Original destination connection id: 99851f84feaec663 (scid: 5354ca6d3ec79f3c) >- CryptoStream[I|ClientHello]
>   Bytes in flight increased to 1200
>   Packet I|0|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 2400
>   Packet PI|1|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 3600
>   Packet PI|2|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 4800
>   Packet PI|3|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 6000
>   Packet PI|4|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight increased to 7200
>   Packet PI|5|L|1200|2  Token=[] CryptoFrame[0,248] Padding(905)
>   Bytes in flight decreased with 7200 to 0 (6 packets RESET)
>   closing receiver
>   Terminating receiver loop because of interrupt
```

**Comment by ptrd** [comment]
2. What results do you get when not running on Android?

**Comment by jjjjjim20** [comment]
I faced with new error :
java.lang.RuntimeException: Missing RSASSA-PSS support

**Comment by ptrd** [comment]
See #27: Use `PlatformMapping.usePlatformMapping(PlatformMapping.Platform.Android)` before starting a connection.

**Comment by ptrd** [comment]
You might also tell how you solved your initial problem(s), as it might help others running kwik on Android.

**Comment by jjjjjim20** [comment]
My previous error (`java.net.ConnectException: Connection timed out after 10000 ms`) fixed with increase connection timeout in android client.

but after adding this `PlatformMapping.usePlatformMapping(PlatformMapping.Platform.Android)` I get new error :
`java.lang.NoClassDefFoundError: Failed resolution of: Lnet/luminis/tls/handshake/TlsStatusEventHandler;`

my agent15 version is 2.2
my kwik version is 0.8.12

Thank you for your responding

**Comment by ptrd** [comment]
Version mismatch.
Kwik 0.8.12 uses agent15 1.1
Kwik 0.8.13 uses agent15 2.0
as documented in the [CHANGELOG](https://github.com/ptrd/kwik/blob/master/CHANGELOG.md)
and specified in the [pom.xml](https://repo1.maven.org/maven2/tech/kwik/kwik/0.8.12/kwik-0.8.12.pom)
