### ISSUE TITLE
Gradle Build fails

### ISSUE THREAD

**Issue by KastenKlicker** [ptrd/kwik#5]
I'm completely new to gradle, so this might be my mistake. After the build failed, I repeated the task with the --scan and this handy page was created. [https://scans.gradle.com/s/gfc7sbepfayly](https://scans.gradle.com/s/gfc7sbepfayly) 

I cloned the project and ran gradle build.
(A maven repository would be nice!)

**Comment by fzn7** [comment]
Hi, your gradle is very old( 4.4.1) Current stable version is 7.0.2 Please try to update.

**Comment by KastenKlicker** [comment]
I know the scan says I'm running gradle 4.4.1, but if I run `gradle -v` it says gradle 7.0.2 is installed. There is no older installation of gradle.

**Comment by fzn7** [comment]
I don`t know what gradle version maintainers are using, I`ve made a fix you can try it: https://github.com/ptrd/kwik/pull/6/files

**Comment by KastenKlicker** [comment]
Thank you for your help, now it works for me.
2 Test failed, but I guess this is not mandatory. [https://scans.gradle.com/s/3wcryyd7h2kkw](https://scans.gradle.com/s/3wcryyd7h2kkw)

**Comment by ptrd** [comment]
fixed, you can now build with gradle 7
