### ISSUE TITLE
Is line 147 of the file 'StreamManager. java' incorrect?

### ISSUE THREAD

**Issue by oren-git** [ptrd/kwik#51]
https://github.com/ptrd/kwik/blob/master/core/src/main/java/net/luminis/quic/stream/StreamManager.java

`peerRole == Role.Client && !bidirectional`
may be
`peerRole == Role.Server && !bidirectional`

**Comment by ptrd** [comment]
Added test case(s) and fix it. Nice catch. Thanks for reporting.
