### ISSUE TITLE
Stop use of generic exception class `Exception`

### ISSUE THREAD

**Issue by Mechite** [ptrd/kwik#52]
Kwik uses the generic `Exception` type across the entire API.

We could either migrate this have the `throws` declarations include the underlying exceptions (which could lead to messy error handling for the users, most likely the reason why `Exception` was used to make a usable API quickly), or we could create simple exception type `QuicException`, adding subclasses in the future, such as `QuikSocketException`.

With the latter case, one would only have to catch generic class `QuicException`.

I will submit a PR to implement the latter.

**Comment by ptrd** [comment]
Hi,
I don't get. I just double checked: there is no single method in the public API classes in net.luminis.quic or net.luminis.quic.server that throws Exception. 
Apart from that, I don't think having a QuicException is a good idea. There is no TcpException in the JDK either. End that has a reason: which transport protocol is used is irrelevant when there is a network error, the caller has just to handle the exception.

**Comment by Mechite** [comment]
> there is no single method in the public API classes
https://github.com/ptrd/kwik/blob/8f821df0d43a8782d1c38157319f467e3b6b3675/core/src/main/java/net/luminis/quic/server/ServerConnector.java#L79

Yes, I agree the transport protocol is irrelevant. `KwikException` would be a better fit.
Except, after further digging, it seems Kwik already has a few custom exceptions built-in, one unique to the builder i just mentioned would be suitable.

> Nor is there any "throw new Exception()" in the code. 
This was not the claim. The underlying exceptions from operations Kwik performs, was simply reduced to `Exception`.

Quoting me here - "was used to make a usable API quickly" - It would likely become a mess if the public API was throwing a bunch of miscellaneous exceptions inc `SocketException` etc when you are just trying to build an instance of `ServerConnector`.

**Comment by ptrd** [comment]
> there is no single method in the public API classes
> [kwik/core/src/main/java/net/luminis/quic/server/ServerConnector.java](https://github.com/ptrd/kwik/blob/8f821df0d43a8782d1c38157319f467e3b6b3675/core/src/main/java/net/luminis/quic/server/ServerConnector.java#L79)
> 
> Line 79 in [8f821df](https://github.com/ptrd/kwik/commit/8f821df0d43a8782d1c38157319f467e3b6b3675)
> 
>  ServerConnector build() throws Exception;

Hahaha, I must have overseen that one. And you are right that this was probably "used to make a usable API quickly", but I should have fixed it before releasing, API methods should not throw "Exception" but something more specific. If that was/is your point, we agree.

> one unique to the builder i just mentioned would be suitable.
Agree. Something along that line would be my preferred solution. I will fix it.

**Comment by ptrd** [comment]
Fixed. 
https://github.com/ptrd/kwik/commit/d54bcbd5aec70be59d744f1cde23c579ce5f0616

**Comment by Mechite** [comment]
Nice.
Searching through for `throws Exception` the only others I see are in tests.

So I definitely made a bold assumption with "across the whole API". Was because this was in a major method
