### ISSUE TITLE
Read / Write from inputStream/ to outputStream  simultaneously

### ISSUE THREAD

**Issue by glush** [ptrd/kwik#54]
Ш'm using kwik from Android Kotlin app. Can I read/write streams in parallel from different coroutines? Or I need to split process - getOutputSteam - write - close - getInputStream - read - close.

**Comment by ptrd** [comment]
Input and output stream are completely independent, they only share the stream ID ;-).
Of course, the application protocol might impose a certain ordering. For example, HTTP/3 requires the request stream to be closed before it sends a response.
Hth
