### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by dragonsKnight5** [ptrd/kwik#7]
can I get an exact list of dependencies?
I keep getting a build failure when attempting to follow the provided instructions

I've attached the build log as well, hopefully someone can point out what my error in this process is
[build log](https://github.com/ptrd/kwik/files/6660123/build.log)

**Comment by ptrd** [comment]
I wonder whether you posted this comment at the wrong project......

(1) the build log mentions maven, this project does not maven
(2) the build log mentions quiche4j, this project is _certainly_ not using quiche, as Kwik is a 100% native Java implementation.

**Comment by dragonsKnight5** [comment]
Yes, I seem to have posted in the wrong place
I think I had too many browser tabs open and mixed up which one I was in
