### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by dragonsKnight5** [ptrd/kwik#8]
Hi,
I have encountered the following issue but can't work out how to resolve it, hopefully someone
here can help me resolve this

> FAILURE: Build failed with an exception.
>
>* Where:
>Build file '/home/James/kwik/build.gradle' line: 23
>
>* What went wrong:
>A problem occurred evaluating root project 'kwik'.
> Could not find method compile() for arguments [{name=agent15}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to >get full insights.

>* Get more help at https://help.gradle.org
>
>BUILD FAILED in 659ms

**Comment by ptrd** [comment]
Strange. I just did a fresh checkout from master and i can execute "gradle build" succesfully.
What version of gradle are you using?
And are you building the lastest commit from this repository, or did you get a different branch from bitbucket?

**Comment by ptrd** [comment]
I assume this is a gradle version issue. I will upgrade gradle build; for now, try to build with gradle version 6.x (i'm using 6.7.1, so that should certainly work)

**Comment by ptrd** [comment]
fixed, see latest commit
