### ISSUE TITLE
git submodule wrong git url

### ISSUE THREAD

**Issue by judos** [ptrd/kwik#9]
Just tried to clone and build kwik but it seems like you moved the agent15 client from github to bitbucket.
Currently i'm getting this error:
```
> git submodule update --init --recursive
Submodule 'agent15' (https://github.com/ptrd/agent15.git) registered for path 'agent15'
Cloning into 'D:/kwik/agent15'...
remote: Repository not found.
fatal: repository 'https://github.com/ptrd/agent15.git/' not found
fatal: clone of 'https://github.com/ptrd/agent15.git' into submodule path 'D:/kwik/agent15' failed
Failed to clone 'agent15'. Retry scheduled
```

Is that repo private or did you just move it to bitbucket? https://bitbucket.org/pjtr/agent15

I updated the file `.gitmodules`:
```
[submodule "agent15"]
	path = agent15
	url = https://bitbucket.org/pjtr/agent15.git
```

And with that it works 😋

**Comment by ptrd** [comment]
Hi, thanks for reporting. The reason this fails is that i made the git modules path relative, so it will work both for https and ssh. It failed, because agent15 repo was not on github. It is now (https://github.com/ptrd/agent15), so it should work now. Please let me know if it doesn't.
